services:
  catalog.db:
    image: postgres:17
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres_catalog:/var/lib/postgresql/data"
  
  basket.db:
    image: postgres:17
    container_name: basket.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDB
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - "postgres_basket:/var/lib/postgresql/data"
        
  distributed.cache:
    image: redis:7.2.4-alpine
    container_name: distributed.cache
    restart: always
    ports:
      - "6379:6379"
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalog.db;Port=5432;Database=CatalogDB;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalog.db
    ports:
      - "6000:8080"
      # - "6060:8081"
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        
  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basket.db;Port=5432;Database=BasketDB;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributed.cache:6379
    depends_on:
      - basket.db
      - distributed.cache
    ports:
      - "6001:8080"
      # - "6061:8081"
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  postgres_catalog:
  postgres_basket: